### ISSUE TITLE
Errors in git command are not passed to lint-diffs

### ISSUE THREAD

**Issue by derrix060** [AtakamaLLC/lint-diffs#19]
Errors in git command are not passed to lint-diffs

```
$  git diff -z origin/non-existing-branch | lint-diffs --strict
fatal: ambiguous argument 'origin/non-existing-branch': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
➜  $ echo $?
0
```

**Comment by isaac-io** [comment]
This isn't really lint-diffs' fault. When piping output there's no way for programs later in the pipeline to know that an earlier step failed. If you want the shell to report the first error in the pipeline rather than the status of the last step you should set the `pipefail` option for shells that support it (see the documentation for Bash for example: https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin).
